some refactoring, new tools and minor bugs fixed

diff --git a/tools/cpp_project/templates/do_build b/tools/cpp_project/templates/do_build
--- a/tools/cpp_project/templates/do_build
+++ b/tools/cpp_project/templates/do_build
@@ -8,32 +8,16 @@ THIS_DIR=$(realpath "$(dirname ${THIS_FILE})")
 [ -f "${THIS_DIR}/build/bin/{{cookiecutter.project_name_lower}}" ] || {
     mkdir -p "${THIS_DIR}/build"
     pushd "${THIS_DIR}/build"
-    cmake .. || {
-      echo "Error configuring (cmake'ing) project"
+    cmake -Wno-dev .. || {
+      echo "Error configuring project"
       exit 1
     }
-    BUILD_LIBS=$(grep -o -E "[a-z_]+_lib" Makefile | sort -u | xargs)
-    BUILD_EXES=$(grep -o -E "[a-z_]+_exe" Makefile | sort -u | xargs)
-    BUILD_TESTS=$(grep -o -E "run_[a-z_]+_tests" Makefile | sort -u | xargs)
 
-    if [ "${BUILD_LIBS}" != "" ]; then
-      make -j $(nproc --all) $(grep -o -E "[a-z_]+_lib" Makefile | sort -u | xargs) || {
-        echo "Error building (make'ing) project libraries"
-        exit 1
-      }
-    fi
-    if [ "${BUILD_EXES}" != "" ]; then
-      make -j $(nproc --all) $(grep -o -E "[a-z_]+_exe" Makefile | sort -u | xargs) || {
-        echo "Error building (make'ing) project executables"
-        exit 1
-      }
-    fi
-    if [ "${BUILD_TESTS}" != "" ]; then
-      make -j $(nproc --all) $(grep -o -E "run_[a-z_]+_tests" Makefile | sort -u | xargs) || {
-        echo "Error building (make'ing) project tests"
-        exit 1
-      }
-    fi
+    cmake --build . || {
+      echo "Error building project"
+      exit 1
+    }
+
     popd
 }
 
